### ISSUE TITLE
Async shell command in steam launch

### ISSUE THREAD

**Issue by schvabodka-man** [Kungsgeten/steam.el#4]
Hello. Would be nice if you'll replace shell-command with async-shell-command. Currently steam.el blocks emacs when playing something, async shell command would be a lot nicer that current state of app.

**Comment by Kungsgeten** [comment]
Hi! I've mostly been using this on Windows, where it for some reason doesn't block Emacs (I think because of some error, actually). I've now switched to `start-process` instead of `shell-command`, which I believe will work.
